### ISSUE TITLE
exponentialDelay doesnt work

### ISSUE THREAD

**Issue by lawloretienne** [silknow/crawler#1]
I tried to set up exponential delay as you have done here

https://github.com/silknow/crawler/blob/443996ec330bb82adc670f2aafee529710383f40/src/crawlers/base.js#L26

but i get the following error

src/index.ts(44,61): error TS2339: Property 'exponentialDelay' does not exist on type 'IAxiosRetry'.

Does this happen for you as well?  Im using the same version of `axios-retry` that you are using : 
`    "axios-retry": "^3.1.1"`

**Comment by ehrhart** [comment]
Related to https://github.com/softonic/axios-retry/issues/58.
As a temporary workaround, you could cast axiosRetry as any:
```js
    retryDelay: (axiosRetry as any).exponentialDelay
```

**Comment by rtroncy** [comment]
@lawloretienne Can we close this issue?
