### ISSUE TITLE
Crawler hang up

### ISSUE THREAD

**Issue by pasqLisena** [silknow/crawler#10]
For two particular cases:
*  `npm start -- met-museum`
*  `npm start -- mfa-boston`
the crawler is hanging, not sending back any console message and not writing any data.

Further testing, I realised that

```js
const axios = require('axios')
axios.get('https://collections.mfa.org/search/Objects/classifications%3ATextiles%3BimageExistence%3Atrue%3BcollectionTer')
    .then(s => console.log(s));
```
after a while it is returned an `Error: socket hang up`.
This is probably related to https://github.com/axios/axios/pull/1752 , solved in https://github.com/axios/axios/commit/93e69625a69ef7bbcf14c9bcb2a1cba2d4b5a126 (not already on npm). However this is weird, because the access to the page via browser is very fast (<1s).

The same behaviour happen also using the `request` module.

-----
node v12.13.1
axios 0.18 and 0.19

**Comment by rtroncy** [comment]
Dependabot has issued the following pull request: https://github.com/silknow/crawler/pull/7 ... related to axios update. Does this have any consequence on this issue?

**Comment by pasqLisena** [comment]
> Dependabot has issued the following pull request: #7 ... related to axios update. Does this have any consequence on this issue?

I have seen an tried the latest axios version (0.19) without any improvement

**Comment by ehrhart** [comment]
I don't observe this issue on met-museum:

```
silknow:crawlers:base Crawling search page 0/0 (offset = 0, limit = 100) +0ms
silknow:crawlers:base Request: { url: 'https://www.metmuseum.org/api/collection/collectionlisting?artist=&department=12&era=&geolocation=&material=Silk%7CTextiles&pageSize=0&showOnly=withImage&sortBy=AccessionNumber', data: null, method: 'get', params: { offset: 0, perPage: 100 } } +2ms
silknow:crawlers:met-museum Downloading record 212227 +0ms
silknow:crawlers:met-museum Downloading record 229026 +447ms
silknow:crawlers:base Downloading file https://images.metmuseum.org/CRDImages/es/original/DP152992.jpg as DP152992.jpg +2s
silknow:crawlers:met-museum Downloading record 231915 +3s
silknow:crawlers:base Downloading file https://images.metmuseum.org/CRDImages/es/original/DP-18047-019.jpg as DP-18047-019.jpg +3s
...
```

However mfa-boston is timing out for 2 reasons. First, it looks like the search URL has been updated to https://collections.mfa.org/objects/list?filter=allClassifications%3ATextiles%3BimageExistence%3Atrue%3BcollectionTerms%3ATextiles%20and%20Fashion%20Arts&page=1.
But even if I change the URL, the crawler still hangs up while crawling the record URL (eg. https://collections.mfa.org/objects/563114). Tried with both axios (0.19.0) and request.

This issue https://github.com/request/request/issues/2047 says to add `Connection: Keep-Alive` to the headers, but even after adding it the request still times out.

**Comment by pasqLisena** [comment]
I pulled your modifications and unexplicably I have

```
Running crawler "met-museum"
Error: TypeError: result.results is not iterable
    at MetMuseumCrawler.onSearchResult (/Users/pasquale/git/silknowcrawler/src/c
rawlers/met-museum/index.js:28:37)
    at MetMuseumCrawler.downloadNextPage (/Users/pasquale/git/silknowcrawler/src
/crawlers/base.js:86:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/pasquale/git/silknowcrawler/src/silknow-crawler.js:40:11
```
when running `npm start -- met-museum `.

Moreover, from which network are you working?

**Comment by ehrhart** [comment]
Sorry for the delay. I was using my home wifi when I tried.

I tried again from work and I get the same error as you. After some debugging, it seems like MET Museum has recently added some extra anti-scrapping security, which requires to proceed by solving a captcha.

If you go to https://www.metmuseum.org/api/collection/collectionlisting?artist=&department=12&era=&geolocation=&material=Silk%7CTextiles&pageSize=0&showOnly=withImage&sortBy=AccessionNumber (from our work network) you might see something like this:

![www.metmuseum.org - Additional security check is required](https://i.imgur.com/y77HqB6.png)

This effectively prevents us from running the crawler for MET Museum.

**Comment by rtroncy** [comment]
Indeed. We will need a formal agreement with MET to be able to crawl again this source.

@tschleider: how problematic is it that we keep working with our last working crawl for this museum?

**Comment by tschleider** [comment]
Right now it is actually a problem w.r.t. the image problem, see https://github.com/silknow/converter/issues/38 based on @pasqLisena 's excellent sum up. MET and MFA are the two sources that need to be re-crawled to make sure not to have broken links

**Comment by ehrhart** [comment]
It seems like disabling the [https agent](https://nodejs.org/api/https.html#https_class_https_agent) (by setting it to `false` in axios config) fixes the crawling issue with Mfa Boston. I'm not exactly sure why but it could come from a misconfigured server on mfa.org, and the way Node.js handles connection pooling.

**Comment by ehrhart** [comment]
Mfa Boston has been re-crawled and the dumps have been updated.
I'll open a new issue for MET Museum.
This issue can be closed.
