### ISSUE TITLE
Crawl data from Fototeca Uffizi, Firenze

### ISSUE THREAD

**Issue by ehrhart** [silknow/crawler#24]
https://fotoinventari.uffizi.it/it/ricerca (Ricerca immagini)
Important remark: this database does not necessarily contain the Uffizi collections, but rather, the holdings of their photographic archive. Substantially it should be the same thing, but there might be exceptions. 

Oggetto: tessuto. 548 records, seemingly quite informative. 
Problems: it’s impossible to search only for those made of silk and not in other materials; circa 25% have no images; images have a watermark, a tiny text (gabinetto fotografico) all over; they are small (400-500 pixels long); text records are almost useless, in terms of cataloging information. 
Similar version, with slightly more focused results from this search, but the same problems: Oggetto: tessuto. 548 records. On the Filtri submenu, on the right, pick Tessuti antichi (javascript:addFilter("id_inventario","47")). This returns 436 records.

---

Addendum for records about paper-based items (point paper plans, drawings, etc.)

We couldn’t find anything relevant.

**Comment by ehrhart** [comment]
Should we still crawl this museum even with the described problems with the results?

**Comment by rtroncy** [comment]
Keep on hold for the moment

**Comment by rtroncy** [comment]
On the [30/04/2021 meeting](https://docs.google.com/spreadsheets/d/1XutXqbPQC5_hUeg_B7gzUh5A2C_zCmKnWLLjNCCG7WU/edit#gid=937636458), we decided to not consider this museum as the data provided is about books containing illustrations of textiles. We will not implement further the FRBRoo additional model that is required.
