### ISSUE TITLE
Crawl data from Collection of the Mobilier national in France

### ISSUE THREAD

**Issue by ehrhart** [silknow/crawler#26]
https://collection.mobiliernational.culture.gouv.fr/recherche

In “Type d’objet” select : Tapisserie﻿, Tissu précieux﻿, ou Vêtement et accessoire﻿, 

In “Matière” select “Textile” then 
in matière select “soie”﻿, 
and in “Technique de tissage” : brocatelle﻿, damas﻿, lampas﻿, reps﻿, satin﻿, ou en velours﻿, 
Période :  select 1500 et 1860﻿

The 2020-05-28 : 568 résults.

---

Addendum for records about paper-based items (point paper plans, drawings, etc.)

We couldn’t find anything relevant.

**Comment by ehrhart** [comment]
Implemented.

[List of known fields](https://github.com/silknow/crawler/wiki/List-of-known-fields#collection-of-the-mobilier-national-in-france) for Collection of the Mobilier national in France.

Records: [mobilier-international_records_20201127_1.tar.gz](https://silknow.uv.es/owncloud/remote.php/webdav/Data/mobilier-international_records_20201127_1.tar.gz)

Files: [mobilier-international_files_20201127_1.tar.gz](https://silknow.uv.es/owncloud/remote.php/webdav/Data/mobilier-international_files_20201127_1.tar.gz)

**Comment by rtroncy** [comment]
For the record, there is a plan for having an API for the Mobilier National, https://collection.mobiliernational.culture.gouv.fr/info#project and this [Github repository](https://github.com/entrepreneur-interet-general/gobelins)
