### ISSUE TITLE
Crawl data from Clark Art Institute

### ISSUE THREAD

**Issue by ehrhart** [silknow/crawler#27]
Some additional references on pattern books. Some discussion is needed as to their incorporation to the KG: all pages, a manual selection, processing requirements…?

Pattern book of silks and damasks
https://digital.clarkart.edu/digital/collection/p16245coll1/id/58429
Decorative textiles : an illustrated book on coverings for furniture, walls and floors, including damasks, brocades and velvets, tapestries, laces, embroideries, chintzes, cretonnes, drapery and furniture trimmings, wall papers, carpets and rugs, tooled and illuminated leathers
https://digital.clarkart.edu/digital/collection/p16245coll1/id/147537
Accessoires du costume et du mobilier depuis le treizième jusqu'au milieu du dixneuvième siècle... Ouvrage contenant 393 phototypies, reproduisant plus de 3.000 documents. (3 volumes)
https://francine.clarkart.edu/record=b1205060~S4

**Comment by rtroncy** [comment]
On the [30/04/2021 meeting](https://docs.google.com/spreadsheets/d/1XutXqbPQC5_hUeg_B7gzUh5A2C_zCmKnWLLjNCCG7WU/edit#gid=937636458), we decided to not consider this museum as the data provided is about books containing illustrations of textiles. We will not implement further the FRBRoo additional model that is required
