### ISSUE TITLE
Crawl data from New York Public Library 

### ISSUE THREAD

**Issue by ehrhart** [silknow/crawler#28]
57 illustrations of historical textiles, made by Charles Kreutzberger, from the classic L’ornement des tissus by DuPont-Auberville.
https://digitalcollections.nypl.org/search/index?filters%5BnamePart_mtxt_s%5D%5B%5D=Kreutzberger%2C%20Charles&keywords=&layout=false#

Crawling these might be the best option. One can also get the same images, plus some other, more heterogeneous at the following links:
up to 1499 & earlier - https://digitalcollections.nypl.org/collections/wallach-division-picture-collection#/?tab=navigation&roots=1228:68221a30-c564-012f-d9ad-58d385a7bc34
1500s - https://digitalcollections.nypl.org/collections/wallach-division-picture-collection#/?tab=navigation&roots=1229:76040460-c564-012f-f7d1-58d385a7bc34
1600s - https://digitalcollections.nypl.org/collections/wallach-division-picture-collection#/?tab=navigation&roots=1230:7ff97690-c564-012f-a616-58d385a7bc34
1700s - https://digitalcollections.nypl.org/collections/wallach-division-picture-collection#/?tab=navigation&roots=1231:84b0b730-c564-012f-295d-58d385a7bc34
1800s (not just from DuPont-Auberville) - https://digitalcollections.nypl.org/collections/wallach-division-picture-collection#/?tab=navigation&roots=1231:84b0b730-c564-012f-295d-58d385a7bc34

**Comment by rtroncy** [comment]
On the [30/04/2021 meeting](https://docs.google.com/spreadsheets/d/1XutXqbPQC5_hUeg_B7gzUh5A2C_zCmKnWLLjNCCG7WU/edit#gid=937636458), we decided to not consider this museum as the data provided is about books containing illustrations of textiles. We will not implement further the FRBRoo additional model that is required
