### ISSUE TITLE
Crawl data from Museo de Arte Sacro El Tesoro de la Concepción (word document)

### ISSUE THREAD

**Issue by rtroncy** [silknow/crawler#30]
The most relevant part of the catalog is in a Word document, available at https://drive.google.com/file/d/1rHyNunC8kDDNIMQs6hGtPCnrd8u4UClM/view?usp=sharing that contains 254 records, “structured” according to a fixed data structure.

Is it possible to process this document into our intermediate JSON format before converting it? There will also be the problem of extracting the images.

**Comment by ehrhart** [comment]
Yes, it is feasible to extract both the content and the images for each record on that Word document.

**Comment by rtroncy** [comment]
Great, can you generate a json file from this word document so that Marie can then propose a mapping? / cc @tschleider

**Comment by ehrhart** [comment]
Implemented.

[List of known fields](https://github.com/silknow/crawler/wiki/List-of-known-fields#museo-de-arte-sacro-el-tesoro-de-la-concepci%C3%B3n) for Museo de Arte Sacro El Tesoro de la Concepción.

Records: [el-tesoro_records_20210325_1.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704156)

Files: [el-tesoro_files_20210325_1.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704161)
