### ISSUE TITLE
Crawl data from the Museo Bellas Artes Valencia (Excel file)

### ISSUE THREAD

**Issue by rtroncy** [silknow/crawler#31]
The data is composed of 1585 records, stored in an Excel file that can be exported in CSV et converted into our intermediate JSON format + a folder containing all images, see https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/UVEG/Data_providers/Museo_BBAA&fileid=34973

The images should have already been copied on the media server, but looking up at https://silknow.org/silknow/media/bbaa/077-90.jpg returns a 404 so this needs to be checked.

**Comment by javier-sevilla** [comment]
Sorry, it is solved.

**Comment by rtroncy** [comment]
On hold given this [warning message](https://lists.eurecom.fr/sympa/arc/silknow/2021-02/msg00006.html).

**Comment by rtroncy** [comment]
On the [30/04/2021 meeting](https://docs.google.com/spreadsheets/d/1XutXqbPQC5_hUeg_B7gzUh5A2C_zCmKnWLLjNCCG7WU/edit#gid=937636458), we decided to not consider this museum as the data provided is too old and the museum is not responsive enough
