### ISSUE TITLE
Crawl data from Musée d'Art et d'Industrie (St Etienne)

### ISSUE THREAD

**Issue by rtroncy** [silknow/crawler#32]
Museum: http://www.musee-art-industrie.saint-etienne.fr/

Logos: we should used the 2 logos attached

- [Saint-Etienne city logo](https://user-images.githubusercontent.com/1051318/103224437-f5b89900-4927-11eb-8c6c-0c4d1abb1df1.png)

- [Museum logo](https://github.com/silknow/crawler/files/5747803/logo-musee.ART-INDUSTRIE-noir.zip)

The data should come in the same format than Joconde but I'm waiting for a confirmation.

**Comment by rtroncy** [comment]
From previous discussion notes, the collection we will have access should be composed of:

- ~360 trimmings (passementrie) from 19th
- ~300 old ribbons (rubans anciens) from 19th
- ~300 sketches (esquisses) from 19th

These descriptions make also use of some controlled vocabularies from Joconde that we need to collect.

**Comment by rtroncy** [comment]
The data has been dropped at https://drive.google.com/drive/folders/1V-p9cJ-lNtUtGHW1ePv_k4rLsd_xbbyb.

The medias are available in the `media` folder.
The metadata is the file `export silknow.tsv`.

@ehrhart Can you convert it into our common JSON format?

The mapping rule for the converter is then discussed on [this thread](https://lists.eurecom.fr/sympa/arc/silknow/2021-01/msg00017.html).

**Comment by ehrhart** [comment]
Implemented.

[List of known fields](https://github.com/silknow/crawler/wiki/List-of-known-fields#mus%C3%A9e-dart-et-dindustrie-st-etienne) for Musée d'Art et d'Industrie (St Etienne).

Records: [musee-st-etienne_records_20210215_1.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704016)

Files: [musee-st-etienne_files_20210215_1.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704108)
