### ISSUE TITLE
[MAD] Persons and roles in "Creation" field

### ISSUE THREAD

**Issue by pasqLisena** [silknow/crawler#34]
The "Creation" field in MAD contains lots of information about the production, namely time, place and involved actors.

For example in 2004.14.106 (848587.json), the filed looks like:

```json
 {
      "label": "Création:",
      "values": [
        "Brossin de Méré",
        " ",
        "Paris",
        "1959",
        "collection printemps-été",
        "Filande e Tessiture Costa",
        " ",
        "Côme",
        "1950-1959"
      ]
 }
```

Looking at http://opac.lesartsdecoratifs.fr/fiche/morceau-de-tissu-8 we note that next to the actors there is:
- a page icon (for going to details). This suggests that we are speaking about a person/institution
- a role, like `créateur textile` or `fabricant textile`

Moreover, `1950-1959` is never there, but this is probably due to a website update.

Is it possible to receive an output like the following?
```json
 {
      "label": "Création:",
      "values": [
        "Author: Brossin de Méré - Role: créateur textile",
        " ",
        "Paris",
        "1959",
        "collection printemps-été",
        "Author: Filande e Tessiture Costa - Role: fabricant textile",
        " ",
        "Côme"
      ]
 }
```
This will help the converter when separating the different information -- see https://github.com/silknow/converter/issues/5

**Comment by ehrhart** [comment]
http://opac.lesartsdecoratifs.fr/ seems to be down (Service Unavailable), and going to http://lesartsdecoratifs.fr/ redirects to http://madparis.fr/, which has a search engine: http://collections.madparis.fr/.

Is this part of the same museum/database?

It might require to rewrite the crawler to use this new website.

**Comment by rtroncy** [comment]
It is from the same museum. Can you check as part of #29 if you would not have to do it anyway?

**Comment by ehrhart** [comment]
@pasqLisena I've updated the crawler. Also now the "Creation" field looks like this:

```
{
    "label": "Création:",
    "values": [
        "Author: Brossin de Méré - Role: créateur textile",
        "Paris",
        "1959",
        "collection printemps-été",
        "Author: Filande e Tessiture Costa - Role: fabricant textile",
        "Côme",
        "1950-1959"
    ]
}
```

Records: [les-arts-decoratifs_records_20210326_3.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704163)
Files: [les-arts-decoratifs_files_20210326_3.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704183)

**Comment by pasqLisena** [comment]
Thanks @ehrhart . We can now close this issue
