### ISSUE TITLE
Crawl data from The Louvre's textile collections

### ISSUE THREAD

**Issue by rtroncy** [silknow/crawler#35]
Web site: https://collections.louvre.fr/

Query:
Time, From 1400 to 1900; 
Material / technique soie; 
Département des Objets d'art du Moyen Age, de la Renaissance et des temps modernes; 
textiles; 
382 results. 

Mappings for @tschleider : https://docs.google.com/document/d/1OWZ2Vr32ODg-HXL4m34YmYkYEaEtqzOb3HqBjHKqjQ4/edit?usp=sharing

See also [this discussion thread](https://lists.eurecom.fr/sympa/arc/silknow/2021-03/msg00126.html)

**Comment by ehrhart** [comment]
Implemented.

[List of known fields for Louvre](https://github.com/silknow/crawler/wiki/List-of-known-fields#louvre).

Records: [louvre_records_20210506_1.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704288)

Files: [louvre_files_20210506_1.tar.gz](https://silknow.uv.es/owncloud/index.php/f/704346)
