### ISSUE TITLE
Add "Subject depicted" to VAM crawler

### ISSUE THREAD

**Issue by ehrhart** [silknow/crawler#36]
The "Subject depicted" field seems to be missing from the currently crawled records (new field?).

However VAM has completely changed their website and API, so it will require to update the crawler then re-crawl everything.

**Comment by rtroncy** [comment]
Is it still worth to do?

**Comment by ehrhart** [comment]
After verification the crawler for VAM has already been updated in 5e5f46c and the information is present in `contentPerson` and `contentOthers` fields.
