### ISSUE TITLE
"Summary" text-field missing in json data for VAM museum

### ISSUE THREAD

**Issue by AvgustinKastelic** [silknow/crawler#4]
Some items in the VAM museum include quite a lot of text in the "Summary" text-field.
This "Summary" tab seems to be absent in json files.
The name suggests it is not important anyway because you would think it is just a summary of other text-fields that are included. But I found a case where this tab provides additional information and might actually be useful for us.
Here is the example:
http://collections.vam.ac.uk/item/O117714/cloak-unknown/
![Summary_tab_or_textfield](https://user-images.githubusercontent.com/44521379/63331568-3e287580-c336-11e9-9a7d-db5373011765.PNG)
And here is a screenshot of O117714.json file with the missing information.
![O117714](https://user-images.githubusercontent.com/44521379/63331380-e12cbf80-c335-11e9-9bde-6097b76d57fb.PNG)

**Comment by ehrhart** [comment]
Already been fixed by 8d2ba24. We now collect all text/numeric fields from the [API of VAM](https://www.vam.ac.uk/api/).

Note: the "Summary" field is called "public_access_description" in the new JSON records files.

**Comment by rtroncy** [comment]
Re-opening and assigning to @tschleider just to confirm that this new json field is actually converted in RDF? Do you need an update of the mapping or do you know how to map it already?

**Comment by tschleider** [comment]
@rtroncy 

I would map it as "S4_Observation", Type: "Summary" which is in line with many other textual fields, see "physical_description" in the mapping e.g. https://docs.google.com/document/d/1ziuh2EiLcuMYDNCn9SUnh4pgQJiH1BY3ZwGg7121SeM/edit#heading=h.vy2q0pvq298w

Does this sound ok?

**Comment by rtroncy** [comment]
Yes, perfect! I suggest you close this issue once you commit changes in the converter that materializes this info in RDF.

Between, it would be good if you could produce a sparql query that returns all possible values of ```E55_Type``` and the context where those values appear since those are candidates for extending the SILKNOW ontology

**Comment by tschleider** [comment]
https://github.com/silknow/converter/commit/ff3f48b06e3a54ead0debd8d041acfa29e080304
