### ISSUE TITLE
Missing documentation about UNIPA

### ISSUE THREAD

**Issue by pasqLisena** [silknow/crawler#6]
It seems that the UNIPA crawler is requiring in input some `csv` files, probably extracted from [this spreadsheet](https://drive.google.com/drive/folders/1gJYv1CbwqknUORdMhPU-BUwr-6lkZ5ki).

This should be documented in the repository.

**Comment by ehrhart** [comment]
Added notes about UNIPA in 8a91e07e3c50ec42fe4413db56cac6d1156226a4 and 271c274998875fa46a648123693a8169509bd830.
