### ISSUE TITLE
MTMAD cannot be crawled anymore

### ISSUE THREAD

**Issue by ehrhart** [silknow/crawler#8]
The museum MTMAD has shut down their search engine (floracci/opac).

There is currently no way to access or search for items in the collections. The collections page (https://www.museedestissus.fr/collections/) currently says "Prochainement" ("Soon").

Once it releases, it will probably require a rewrite of the MTMAD crawler.

**Comment by rtroncy** [comment]
Bummer! @tschleider Why exactly did we have to re-crawl this museum? What are we missing from our current snapshot?

**Comment by ehrhart** [comment]
We were missing the local filename for the photos. I have made a script which processes the last snapshot we have and adds that information to the records files.

The dumps have been updated on owncloud (mtmad_files.tar.gz and mtmad_records.tar.gz).

**Comment by rtroncy** [comment]
Wow, super great! Thanks @ehrhart !

However, you put the files in '/SILKNOW/TEMPORAL_DATA (removed soon)', right? Can you put the tar gz files in '/data/'?

Note for @tschleider , can re-convert this dataset?

**Comment by tschleider** [comment]
Yes, thanks @ehrhart !

@rtroncy For ownCloud, Javier has still not copied the files into the direct location (instructions: delete everything in /data/ except UNIPA and GARIN and replace it with temporal_data) as long has he has not done it it's probably better to keep it together. Is it possible for you @ehrhart to copy files around on ownCloud or do I even have the rights? Then we should maybe do that ourselves.

@rtroncy  yes, this is on its way.

**Comment by rtroncy** [comment]
@tschleider You should have the rights ... if not, ask for them.

**Comment by rtroncy** [comment]
Update: we may not need to crawl MTMAD anymore if we have an agreement to directly use an export of their database. See https://drive.google.com/drive/folders/1Y1bIt0Z-9iQrwShTi858cqbS8LlMzPLV for a possible export. An alternative will be in the Joconde format.

**Comment by rtroncy** [comment]
Edit: this update was misleading, the URL above points to another museum source but not MTMAD for which the problem remains

**Comment by tschleider** [comment]
I forgot to update this, but it's all long done, @ehrhart updated the files and it's all on owncloud since a long while: 
https://silknow.uv.es/owncloud/index.php/apps/files/?dir=/Data&fileid=626898
