### ISSUE TITLE
Les art decoratifs website is down

### ISSUE THREAD

**Issue by pasqLisena** [silknow/crawler#9]
The website http://collections.lesartsdecoratifs.fr is down and it is not possible to crawl it (with `npm start -- les-arts-decoratifs`).

The website is still referenced in the [MAD website](https://madparis.fr/francais/musees/musee-des-arts-decoratifs/collections/) .

**Comment by rtroncy** [comment]
Thanks for the info @pasqLisena. Fortunately, we still have the old crawl. Did you need something specific in attempting to re-crawl the collection?

**Comment by ehrhart** [comment]
The website seems to be up as of today. Crawling works.

**Comment by rtroncy** [comment]
Correct! @pasqLisena Did you need to re-crawl this museum source or can we close this issue?

**Comment by pasqLisena** [comment]
We can indeed close
